# Data
train_paths:
  - "/home/ruppulur/repos/rope-manipulation/datasets/2022-04-22-16:15:12" 
  - "/home/ruppulur/repos/rope-manipulation/datasets/2022-04-13-15:59:58"
  - "/home/ruppulur/repos/rope-manipulation/datasets/2022-04-13-15:59:22"
  - "/home/ruppulur/repos/rope-manipulation/datasets/2022-04-13-15:54:41"
  - "/home/ruppulur/repos/rope-manipulation/datasets/2022-04-22-16:15:12" 
test_paths:
  - "/home/ruppulur/repos/rope-manipulation/datasets/2022-04-13-03:43:14"
out_dir: "state_dicts_inv_dyn"
img_size: 64

# Model
betas: [0.5, 0.999]

rope_site_range: [0, 9]
rope_site_dim: 10 # site
angle_range: [-3.141592653589793, 3.141592653589793]
angle_dim: 30
length_range: [0.02, 0.5]
length_dim: 10

# Training
batch_size: 30
lr: 0.0001
epochs: 200